version: 2
jobs:
  build:
    docker:
      - image: node:7.10.1
    steps:
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm test
